GFoods/Areas/Admin/Controllers/CompanyController.cs
using GFoods.DataAccess.Repository;
using GFoods.DataAccess.Repository.IRepository;
using GFoods.Models;
using GFoods.Models.ViewModels;
using GFoods.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace GFoods.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {

            List<Company> listCompany = _unitOfWork.Company.GetAll().ToList();
            return View(listCompany);
        }
        public IActionResult Upsert(int? id)
        {
            
            
            if (id == null || id == 0)
            {
                return View(new Company());
            }
            else
            {
                Company companyObj = _unitOfWork.Company.Get(x => x.Id == id);
                return View(companyObj);
            }
        }
        [HttpPost]
        public IActionResult Upsert(Company companyObj)
        {

            if (ModelState.IsValid)
            {
                
                if (companyObj.Id == 0)
                {
                    _unitOfWork.Company.Add(companyObj);
                }
                else
                {
                    _unitOfWork.Company.Update(companyObj);

                }
                _unitOfWork.Save();
                TempData["Success"] = "Success Create";

                return RedirectToAction("Index");
            }
            else
            {
                
                return View(companyObj);
            }
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> objProductList = _unitOfWork.Company.GetAll().ToList();
            return Json(new { data = objProductList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var companyToBeDeleted = _unitOfWork.Company.Get(x => x.Id == id);
            if (companyToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            
            _unitOfWork.Company.Remove(companyToBeDeleted);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion



    }
}

GFoods/Areas/Admin/Controllers/ProductController.cs
using GFoods.DataAccess.Repository;
using GFoods.DataAccess.Repository.IRepository;
using GFoods.Models;
using GFoods.Models.ViewModels;
using GFoods.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace GFoods.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Product> listProduct = _unitOfWork.Product.GetAll(includeProperties: "CategoryProduct").ToList();
            return View(listProduct);
        }
        public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> CategoryList = _unitOfWork.CategoryProduct.GetAll().Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });
            ViewBag.CategoryList = CategoryList;
            ProductVM productVM = new()
            {
                CategoryList = CategoryList,
                Product = new Product()
            };
            if (id == null || id == 0)
            {
                return View(productVM);
            }
            else
            {
                productVM.Product = _unitOfWork.Product.Get(x => x.Id == id, includeProperties: "ProductImages");
                return View(productVM);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVM, List<IFormFile>? files)
        {

            if (ModelState.IsValid)
            {
                if (productVM.Product.Id == 0)
                {
                    productVM.Product.CreatedDate = DateTime.Now;
                    productVM.Product.ModifiedDate = DateTime.Now;
                    productVM.Product.CreatedBy = User.Identity.Name;
                    productVM.Product.ModifiedBy = User.Identity.Name;
                    if (string.IsNullOrEmpty(productVM.Product.SeoTitle))
                    {
                        productVM.Product.SeoTitle = productVM.Product.Title;
                    }
                    if (string.IsNullOrEmpty(productVM.Product.Alias))
                    {
                        productVM.Product.Alias = GFoods.Models.Common.Filter.FilterChar(productVM.Product.Title);
                    }
                    _unitOfWork.Product.Add(productVM.Product);
                }
                else
                {
                    productVM.Product.ModifiedDate = DateTime.Now;
                    productVM.Product.ModifiedBy = User.Identity.Name;
                    productVM.Product.Alias = GFoods.Models.Common.Filter.FilterChar(productVM.Product.Title);
                    _unitOfWork.Product.Update(productVM.Product);

                }
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (files != null)
                {
                    foreach (var file in files)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        string productPath = @"images\products\product-" + productVM.Product.Id;
                        string finalPath = Path.Combine(wwwRootPath, productPath);
                        if (!Directory.Exists(finalPath))
                            Directory.CreateDirectory(finalPath);
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        ProductImages productImages = new ProductImages()
                        {
                            ImageUrl = @"\" + productPath + @"\" + fileName,
                            ProductId = productVM.Product.Id,

                        };
                        if (productVM.Product.ProductImages == null)
                            productVM.Product.ProductImages = new List<ProductImages>();

                        productVM.Product.ProductImages.Add(productImages);
                    }
                    _unitOfWork.Product.Update(productVM.Product);
                    _unitOfWork.Save();
                }



                _unitOfWork.Save();
                TempData["Success"] = "Thành công";

                return RedirectToAction("Index");
            }
            else
            {
                productVM.CategoryList = _unitOfWork.CategoryProduct.GetAll().Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
                return View(productVM);
            }
        }
        public IActionResult DeleteImage(int imageId)
        {
            var imageToBeDeleted = _unitOfWork.ProductImage.Get(u => u.Id == imageId);
            var productId = imageToBeDeleted.ProductId;
            if (imageToBeDeleted != null)
            {
                if (!string.IsNullOrEmpty(imageToBeDeleted.ImageUrl))
                {
                    var oldImagePath =
                        Path.Combine(_webHostEnvironment.WebRootPath, imageToBeDeleted.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork.ProductImage.Remove(imageToBeDeleted);
                _unitOfWork.Save();
                TempData["success"] = "Xóa thành công!";
            }
            return RedirectToAction(nameof(Upsert), new { id = productId });
        }


        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "CategoryProduct").ToList();
            return Json(new { data = objProductList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork.Product.Get(x => x.Id == id);
            if (productToBeDeleted == null)
            {
                return Json(new { success = false, message = "Lỗi khi xóa" });
            }
            string productPath = @"images\products\product-" + id;
            string finalPath = Path.Combine(_webHostEnvironment.WebRootPath, productPath);
            if (Directory.Exists(finalPath)) {
                string[] filePaths = Directory.GetFiles(finalPath);
                foreach (string filePath in filePaths)
                {
                    System.IO.File.Delete(filePath);
                }
                Directory.Delete(finalPath);
            }
            _unitOfWork.Product.Remove(productToBeDeleted);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Xóa thành công" });
        }

        #endregion



    }
}

GFoods/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Danh sách công ty </h2>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-10">
        </div>
        <div class="col-2 text-end">
            <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle-fill"></i> Tạo công ty mới
            </a>
        </div>
    </div>
    <div class="card-body p-4">
        
        <table id="tblData" class="table table-bordered table-striped" style="width="100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Phone number</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts {
    <script src="~/js/company.js">
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

GFoods/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id != 0 ? "Cập nhật" : "Tạo") Công ty</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div asp-validation-summary="ModelOnly"></div>
                        <div class="form-floating py-2 col-12">
                            <label asp-for="Name" class="ms-2"></label>
                            <input asp-for="Name" class="form-control border-0 shadow" autofocus />
                            <span asp-validation-for="Name" class=" text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <label asp-for="PhoneNumber" class="ms-2"></label>
                            <input asp-for="PhoneNumber" class="form-control border-0 shadow" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>

                        </div>
                        <div class="form-floating py-2 col-12">
                            <label asp-for="StreetAddress" class="ms-2"></label>
                            <input asp-for="StreetAddress" class="form-control border-0 shadow" />
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <label asp-for="City" class="ms-2"></label>
                            <textarea asp-for="City" class="form-control border-0 shadow"></textarea>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <label asp-for="PostalCode" class="ms-2"></label>
                            <input asp-for="PostalCode" class="form-control border-0 shadow" />
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
                        
                        <div class="row mt-3">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Cập nhật</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Tạo</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Product" asp-action="Index" class="btn btn-outline-primary border form-control">Back to list</a>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            
        </form>
    </div>
</div>
@section Scripts {
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
            toolbar_mode: 'floating',
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />

    }
}